### PR TITLE
Add retry logic to create_run

### PR DESCRIPTION
**Pull request by j316chuck**
# Description
Add retry logic to create_run

# Issues Fixed
Tests failed here because create_run timed out 
https://github.com/mosaicml/composer/actions/runs/11452297889/job/31901019192#step:3:348

Adding a retry here should help

### CODE REVIEW

**Review by snarayan21 — COMMENTED** [review]
should we just increase timeout? i don't mind either way, up to @b-chu

**Comment by b-chu** [comment]
I think it's better to increase timeout in `create_run` and no have retry logic. Should be ok to overload the run's max_duration and use that timeout for `create_run` as well

**Comment by j316chuck** [comment]
bumped timeout to 30 seconds. for corgi the retry def helped a lot so i think we should keep wdyt? it'll max delay it by 2 minutes which I think is appropriate?

**Comment by b-chu** [comment]
Let's just do timeout for now and if run creation keeps timing out, we can add backoff later

**Comment by j316chuck** [comment]
sounds good fixed

**Review by b-chu — APPROVED** [review]
Untested but Chuck said he'd fix if there's any issues

**Pull request merged**
